### ISSUE TITLE
No Audio For No Apparent Reason

### ISSUE THREAD

**Issue by ArybellaHope** [stephend/kaniwani-audio#2]
I've had this installed for several months, but have never once had any audio play. I also have KaniWani Blur installed, if that causes a conflict. Is there something I need to change, or is this just out of date? Thanks.

**Comment by stephend** [comment]
Hi, this script hasn't worked for a long time after some changes to both WK and KW. Some other KaniWani users have made a new version that seems to work, there's a forum thread at https://community.wanikani.com/t/userscript-kaniwani-audio/19314/37
